// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details-holder': string;
  'has_sub': string;
}
export const cssExports: CssExports;
export default cssExports;
