// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delino': string;
  'left': string;
  'main-footer': string;
  'right': string;
  'social-list': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
