// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lds-ring': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
