export const FETCH_MENU = 'FETCH_MENU';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const LIKED_PRODUCT = 'LIKED_PRODUCT';
export const DISLIKED_PRODUCT = 'DISLIKED_PRODUCT';
