// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grecaptcha-badge': string;
  'rc-anchor-light': string;
  'recaptcha_area': string;
  'recaptchatable': string;
  'register_box': string;
}
export const cssExports: CssExports;
export default cssExports;
