// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ancBox': string;
  'food_menu': string;
  'img': string;
  'lightBox': string;
  'lightInner': string;
  'modalBox': string;
  'parent-modal': string;
}
export const cssExports: CssExports;
export default cssExports;
