// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'custom-checkbox': string;
  'disabled': string;
  'filter-box': string;
  'filter-check': string;
  'filter-search': string;
  'placeholder': string;
  'search-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
