// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'ingredient': string;
  'modal-food': string;
  'price': string;
}
export const cssExports: CssExports;
export default cssExports;
