// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-coupon': string;
  'add-coupon-holder': string;
  'anc-coupon-form': string;
  'cart-bottom': string;
  'cart-quantity': string;
  'cart-total': string;
  'empty-cart': string;
  'fo': string;
  'rest-menu-holder': string;
  'row': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
