// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cartInfoFood': string;
  'details-holder': string;
  'tittle': string;
  'tittle-food': string;
}
export const cssExports: CssExports;
export default cssExports;
