// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'left': string;
  'logo-holder': string;
  'main-header': string;
  'rest-logo-holder': string;
  'right': string;
  'user-holder': string;
  'user-login-holder': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
