// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryList': string;
  'cover-container': string;
  'logo-holder': string;
  'offline': string;
  'online-status': string;
  'rest-cover': string;
  'rest-logo-holder': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
