// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cartInfoFood': string;
  'price': string;
}
export const cssExports: CssExports;
export default cssExports;
